### PR TITLE
Fixed Text Overflow on mobile UI

### PR DESCRIPTION
**Pull request by ForchaGlen**
**Before**
Screenshot from 2022-03-21 18-18-44

**After**
Screenshot from 2022-03-21 18-17-35

### CODE REVIEW

**Comment by RaphaelRobidas** [comment]
Nice, thank you!

Can you put the CSS in a separate file instead of `bulma.min.css`? This file might be replaced by more recent versions of the framework.

Also, for the future pull requests, it would be better to ask to merge in the `develop` branch. Changes on the `master` branch automatically create a new Docker image and triggers updates on everyone using the image. I verify the stability of the platform and run tests before merging to `master`. I'll just change the branch for this pull request.

**Comment by ForchaGlen** [comment]
> Nice, thank you!
> 
> Can you put the CSS in a separate file instead of `bulma.min.css`? This file might be replaced by more recent versions of the framework.
> 
> Also, for the future pull requests, it would be better to ask to merge in the `develop` branch. Changes on the `master` branch automatically create a new Docker image and triggers updates on everyone using the image. I verify the stability of the platform and run tests before merging to `master`. I'll just change the branch for this pull request.

Sorry for the master and develop branch mix up. 
I have made the requested changes. I still learning how to delete a commit from a pull request , I mistakenly deleted file`bulma.min.css ` but I re-uploaded the original file. sorry for the mixup.

**Comment by RaphaelRobidas** [comment]
This PR looks good and it works great for molecule names. I do notice however that it affects the calculations page:
image

Before the PR, it looks like this:
image

It would be great if you could look over the style of the calculations. Long titles probably don't wrap correctly there either, so you could look into that (either in this PR or in the future). For short titles (as in the screenshot), the style should remain the same (icon on the same line as the title, no line return and blank line).

**Comment by ForchaGlen** [comment]
Thank you for the review , the required changes have been made. here is the new look
image

**Comment by RaphaelRobidas** [comment]
Looking good, thanks!

**Pull request merged**
